# Generated by Django 3.2.10 on 2021-12-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210426_2349'),
        ('customer', '0003_auto_20210427_1115'),
    ]

    operations = [
    ]
